### PR TITLE
STABLE-6: Backport fixes from master.

### PR DESCRIPTION
**Pull request by eric-ch**
Commits from upstream that should be backported in stable-6.

### CODE REVIEW

**Comment by eric-ch** [comment]
OXT-983
OXT-964

**Comment by eric-ch** [comment]
http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/712

**Comment by eric-ch** [comment]
http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/714

**Comment by rossphilipson** [comment]
Tested with above build. Successfully installed Ubuntu 16.10, CentOS 7 and Debian 8 (all 64b). Fedora 24 did not work but for a different reason (will update ticket). LGTM, merging soon.

**Pull request merged**
