### PR TITLE
Stable 6: OXT-699 : linux viptables: return errors and fix userspace access

### PR DESCRIPTION
**Pull request by dozylynx**
Fixes to the three viptables operations: add, remove, list

Do not squash error codes returned by the hypercalls.
Copy arguments and results to and from userspace correctly.

Signed-off-by: Christopher Clark christopher.clark6@baesystems.com
(cherry picked from commit d57c2508e9a490e4ca7b814ce7c90f607ec46735)

### CODE REVIEW

**Comment by jean-edouard** [comment]
Built here: http://158.69.127.133:8020/builders/openxt-custom/builds/126
Smoke-tested with large v4v transfers, LGTM.

**Comment by jean-edouard** [comment]
Actually viptables doesn't seem to work anymore with these changes... (at least -D and -F, -A seems to work)
-D works when specifying a rule, but doesn't when just using a rule ID (like `viptables -D25`).

**Comment by jean-edouard** [comment]
Maybe the viptables tool should also be updated to report the new return values.

**Comment by dozylynx** [comment]
ok, this PR for the kernel module code is fixed and I've refreshed the branches.
For the delete operation, the code in this PR wasn't allowing a NULL rule through the new copy-to-and-from-userspace code, which it needed to.

In testing this, I have learned that it is essential to understand how to use the command line tool. It took far longer than it should have to find out that:
 `viptables -D 24`
is wrong but proceeds to delete the last rule in the list and return 'ok'
whereas:
`viptables -D24`
does the expected thing, deleting rule 24.

I agree that the tool should be updated to report the return values.

**Comment by dozylynx** [comment]
diff versus the earlier patch:

```
diff --git a/v4v/v4v.c b/v4v/v4v.c
index 2b17912..d48157f 100644
--- a/v4v/v4v.c
+++ b/v4v/v4v.c
@@ -3557,9 +3557,14 @@ v4v_ioctl (struct file *f, unsigned int cmd, unsigned long arg)
         if (copy_from_user (&rule_pos, (void __user *)arg,
                             sizeof(struct v4v_viptables_rule_pos)))
           return -EFAULT;
-        if (copy_from_user (&rule, rule_pos.rule, sizeof(struct v4v_viptables_rule)))
-          return -EFAULT;
-        rc = v4v_viptables_del (p, &rule, rule_pos.position);
+        if (rule_pos.rule)
+        {
+          if (copy_from_user (&rule, rule_pos.rule, sizeof(struct v4v_viptables_rule)))
+            return -EFAULT;
+          rc = v4v_viptables_del (p, &rule, rule_pos.position);
+        }
+        else
+          rc = v4v_viptables_del (p, NULL, rule_pos.position);
       }
       break;
     case V4VIOCVIPTABLESLIST:
```

**Comment by dozylynx** [comment]
Here's a draft changeset for plumbing the result codes through the command line tool:
https://github.com/dozylynx/v4v/commit/bbc2a3efcf7c476759664fe2b61dc7a2a3c34f8a

Have not submitted that tool patch as a PR as it has not been tested yet, though it does compile ok.

**Comment by rossphilipson** [comment]
Tested that viptables -D and -F work fine with this version.

**Comment by rossphilipson** [comment]
Tested further, LGTM. Merging soon.

**Pull request merged**
