### PR TITLE
S9: [xen] Bring macros in line with Xen 4.12

### PR DESCRIPTION
**Pull request by tsirakisn**
OXT-1454
Merge with: https://github.com/OpenXT/xenclient-oe/pull/1166

Signed-off-by: Nicholas Tsirakis <tsirakisn@ainfosec.com>

### CODE REVIEW

**Comment by dozylynx** [comment]
Looks good.

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6583

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6593

**Comment by jean-edouard** [comment]
LGTM, merging soon.

**Pull request merged**
