### PR TITLE
OXT-700 : v4v ioctl: remove userspace pointer dereferences

### PR DESCRIPTION
**Pull request by dozylynx**
Use copy_from_user, copy_to_user, get_user and put_user access
methods with userspace pointers in the ioctl code.

In order to be able to use variables on the kernel stack as
parameters to inner functions, remove access_ok where required.

Signed-off-by: Christopher Clark christopher.clark6@baesystems.com

### CODE REVIEW

**Comment by dozylynx** [comment]
Corrections since the version included in the earlier PR:
- Removed `access_ok` in `v4v_recvfrom` where previously it had been present.
  This would likely have caused breakage since the kernel stack pointer supplied would not pass this check.
- In `V4VIOCCONNECT`, allow the argument to be `NULL` and invoke `v4v_connect` with `NULL` if that was supplied.
- In `V4VIOCRECV`, copy the address variable back to the user after the `v4v_recvfrom` function completes since this can be used to return the address of the peer.

**Comment by eric-ch** [comment]
`In V4VIOCCONNECT, allow the argument to be NULL and invoke v4v_connect with NULL if that was supplied.`
-1, it will fault, so it should return with EFAULT before that.

**Comment by dozylynx** [comment]
@eric-ch : can you follow this code path in the `V4VIOCCONNECT` ioctl:

beforehand:

```
p->ptype = V4V_PTYPE_DGRAM
p->state = V4V_STATE_CONNECTED
```

then:

```
V4VIOCCONNECT ( arg = NULL, nonblock = doesntmatter )
```

-> this will `return 0` (ie. success) and `p->state = V4V_STATE_BOUND`.

From this, I infer that `NULL` is a valid argument to `v4v_connect` and so we have to implement the path that supports `NULL` to avoid a change of user-visible behaviour.

**Comment by dozylynx** [comment]
Discussed with @eric-ch .  `NULL` is indeed a valid argument, but only for datagrams, so introduce a new check prior to handling stream connections. Have pushed a revised cset to the PR branch.

**Comment by eric-ch** [comment]
@dozylynx It seems to be supporting DGRAM connection "disconnect" (reverting to BOUND). I can only think this is not so widely used (prefering `sendto()`/`recvfrom()` instead). That should be working, at first glance...
This is all to keep changes minimal I understand, but splitting `v4v_connect()` in `v4v_connect_stream()` and `v4v_connect_dgram()` would be easier, also the default binding can probably be done beforehand, even if it can still fail after.

**Comment by eric-ch** [comment]
+1.
Basic testing went without problem.

**Pull request merged**
