### PR TITLE
Stable 6 : OXT-693 : add handling of v4v port exhaustion

### PR DESCRIPTION
**Pull request by dozylynx**
Signed-off-by: Christopher Clark christopher.clark6@baesystems.com
(cherry picked from commit 8358232c26605c3f8d61fb6f34c230cb1df1679f)

### CODE REVIEW

**Comment by jean-edouard** [comment]
Built here: http://158.69.127.133:8020/builders/openxt-custom/builds/126
Smoke-tested with large v4v transfers, LGTM.

**Comment by jean-edouard** [comment]
- Why isn't `V4V_PORTS_EXHAUSTED` in a `#define`?
- The first chunk of the patch looks like a cosmetic change.

**Comment by dozylynx** [comment]
> Why isn't V4V_PORTS_EXHAUSTED in a #define?

Since we're checking for overflow, my preference was for the compiler to know the correct type for the limit value and complain if the type of ip.addr.port was changed. It could be a `#define` though if that would be preferred - fine with me either way.

> The first chunk of the patch looks like a cosmetic change.

Yes, the middle chunk is removal of redundant code. It can be dropped from the change if necessary.

**Comment by rossphilipson** [comment]
This was discussed, the cosmetic part was removed, the rest looks good. Merging soon.

**Pull request merged**
