### PR TITLE
OXT-978: Silence warnings due to the build-system

### PR DESCRIPTION
**Pull request by eric-ch**
General refactoring of the autotools build system to simplify and update the existing. This include removal of header generation, version management done in the configure.ac and re-arrangement of the project headers to reflect that.

Add a check at configure for Xen and Linux V4V headers (e.g, building from libv4v directory ```./configure CFLAGS="-I../v4v/include -I../v4v" CPPFLAGS="-I../v4v/include -I../v4v"``` will point to the headers in this repo).

Refresh the sbuild configuration, there are still a couple of lintian errors and warnings:
```W: libv4v: package-name-doesnt-match-sonames libv4v-1.0-0 libv4v-nointerposer-1.0-0
E: libv4v: extended-description-is-empty
W: libv4v: binary-without-manpage usr/bin/libv4v-config
W: libv4v: binary-without-manpage usr/bin/ttcp-v4v
W: libv4v: binary-without-manpage usr/bin/v4v-proxy
W: libv4v: binary-without-manpage usr/bin/viptables
E: libv4v: non-empty-dependency_libs-in-la-file usr/lib/libv4v.la
E: libv4v: non-empty-dependency_libs-in-la-file usr/lib/libv4v_nointerposer.la
```

Refresh the RPM configuration and silence warnings with libtool, also reduce the verbosity of ```make``` and ```libtool``` in general.

### CODE REVIEW

**Comment by eric-ch** [comment]
See related PR: https://github.com/OpenXT/openxt/pull/241

**Comment by jean-edouard** [comment]
This is how the build fails for Debian:
```
aclocal: couldn't open directory 'm4': No such file or directory
autoreconf: aclocal failed with exit status: 1
dh_autoreconf: autoreconf -f -i returned exit code 1
make: *** [build-arch] Error 2
dpkg-buildpackage: error: debian/rules build-arch gave error exit status 2
```

**Comment by eric-ch** [comment]
Last commit should take care of m4 directory. Since it is not versioned it was probably still in my tree which would explain why I could build.

**Comment by eric-ch** [comment]
Build [806](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/806). Passes smoke testing on E6440.
Related PRs:
https://github.com/OpenXT/xenclient-oe/pull/613
https://github.com/OpenXT/openxt/pull/241
https://github.com/OpenXT/v4v/pull/29

**Comment by jean-edouard** [comment]
Builds fine, and green!! Boots fine too. Code LGTM.
+1

**Review by jean-edouard — APPROVED** [review]

**Review by dpsmith — APPROVED** [review]
RM Reviewed-by: dpsmith@apertussolutions.com

**Comment by jean-edouard** [comment]
Merging soon.

**Pull request merged**
